name: Build and Release Binary on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.1'

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Build the binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o bin/commit-prompt .

      - name: Commit binary
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add bin/commit-prompt
          git commit -m "Add binary for ${{ github.ref }}"
          git push
